### ISSUE TITLE
fz_bbox not found ed other error

### ISSUE THREAD

**Issue by caste1969** [MishaUliutin/MuPDF.WinRT#1]
Hi, I try to compile your wrapper with the latest version of mupdf sources, and I find a lot of error, like fz_bbox not defined and some function with different number of parameter. Perhaps have you create this wrapper with different version on mupdf?
Thanks in adavance.
caste

**Comment by MishaUliutin** [comment]
Hi, I have not completely finished this wrapper yet, so there is no simple steps to compile it (the main problem now is asm code in OpenJPEG library which is used by mupdf and asm code is denied for ARM architecture in VS2012 compiler), but if you want I could describe  steps how to compile it now or just send you compiled binary files.

P.S. I used the latest released version of MuPDF 1.1

Best Regards,
Misha Uliutin

**Comment by caste1969** [comment]
Hi Misha, Thanks for your replay. I find your project very interesting.Using your file I have compiled the win8 project, with the latest version of mupdf.So now I have the 3 lib, in debug dir. For Arm the problem is like in this post:http://social.msdn.microsoft.com/Forums/en-US/winappswithnativecode/thread/72588182-d22c-417e-836f-77ddec78ee38/and I simply use the this like for ARM: return (long)((f>0.0f) ? (f + 0.5f):(f -0.5f));
Now I use your wrapper to create library.And I find that the fz_bbox has been removed in the latest library, and I replace with fz_irect(?) ..., and so on.
Have you a project demo where use your library?Please, could you give me some help on how I can finish the migration to new versione mupdf of your wrapper.?What you mean when say that 'the wrapper is not completely '?
Thanks in advance
caste

**Comment by MishaUliutin** [comment]
> > Have you a project demo where use your library?

yes this is part of my project for test library (I plan to create documentation in Wiki and commit some demo projects):

``` C#
        private void DrawFirstPage()
        {
            var data = GetPDFFileData();
            using (var document = Document.Create(
                data.AsBuffer(), // - file
                DocumentType.PDF, // type
                160) // - dpi
                )
            {
                MuPDFWinRT.Point size = document.GetPageSize(0);
                var image = new WriteableBitmap(size.X, size.Y);
                document.DrawPage(0, image.PixelBuffer, 0, 0, size.X, size.Y, false);
                image.Invalidate();
                //_test - image
                _test.Source = image;
            }
        }

        private byte[] GetPDFFileData()
        {
            using (var stream = typeof(MainPage).GetTypeInfo().Assembly
                .GetManifestResourceStream("TestWinRTProj.1.pdf"))
            {
                var buff = new byte[stream.Length];
                stream.Read(buff, 0, buff.Length);
                return buff;
            }
        }
```

> > Please, could you give me some help on how I can finish the migration to new versione mupdf of your wrapper.?

yes, what version of mupdf do you use?

> > What you mean when say that 'the wrapper is not completely '?

the main issues now are more "simple" compile process, without necessary change the code of third libraries and documentation. In the next version I am planning to add multi threading drawing and JavaScipt support.

P.S.
This is my instruction for compile now, sorry for some additional work:
Go to folder with project and run:

```
    $ git submodule init
    $ git submodule update
```

Go to folder ./MuPDF.WinRT/ThirdParty/mupdf and run:

```
    $ git submodule init
    $ git submodule update
```

Find file  ./MuPDF.WinRT/ThirdParty/mupdf/fitz/base_time.c and change (this is for Win8 version, because under Win8 store application Winsock2 has limitation ):

``` C
struct timeval;
```

to

``` C
#ifdef WRTSA
struct timeval {
        long    tv_sec;         /* seconds */
        long    tv_usec;        /* and microseconds */
};
#else
struct timeval;
#endif
```

Find file ./MuPDF.WinRT/ThirdParty/mupdf/thirdparty/openjpeg/libopenjpeg/opj_includes.h and change:

``` C
static INLINE long lrintf(float f){
#ifdef _M_X64
    return (long)((f>0.0f) ? (f + 0.5f):(f -0.5f));
#else
    int i;

    _asm{
        fld f
        fistp i
    };

    return i;
#endif
}
```

to

``` C
static INLINE long lrintf(float f){
//#ifdef _M_X64
    return (long)((f>0.0f) ? (f + 0.5f):(f -0.5f));
//#else
//    int i;
//
//    _asm{
//        fld f
//        fistp i
//    };
//
//    return i;
//#endif
}
```

Open project ./MuPDF.WinRT/ThirdParty/mupdf/win32/mupdf.sln and build project - generated (this will generate some auto generated files for mupdf)

Open project ./MuPDF.WinRT/Third Party/Win8/Win8.sln and build it for all configurations (Win32|Debug, Win32|Release, ARM|Debug, ARM|Release). As result you will have all necessary static libraries for build project for Win8 or WP8

**Comment by caste1969** [comment]
Hi, Thanks again, I take a snapshot from source code of Mupdf using   this link:http://git.ghostscript.com/?p=mupdf.git;a=snapshot;h=9d20a4f3a69fdea855f8678c1ad50b5db7472d81;sf=tgzat this page:http://git.ghostscript.com/?p=mupdf.git;a=summary
Marco

Date: Fri, 22 Feb 2013 14:30:32 -0800

**Comment by onkar1987** [comment]
Hi Misha,
Thanks for you great work. I am just facing the problem in `image.PixelBuffer`
and namespace using is System.Windows.Media.Imaging so the `WriteableBitmap` is not support the `PixelBuffer`. I am new to windows phone 8 development. can you please help. or upload some windows phone 8 code to view the PDF file in widows phone 8 application. Thanks once again.

**Comment by MishaUliutin** [comment]
Hi,
you could find example of using MuPDF in this project https://bitbucket.org/mishauliutin/pdf-reader-for-wp8-public in this class https://bitbucket.org/mishauliutin/pdf-reader-for-wp8-public/src/f112ff85aab430e018eb396b45fce903bbf86ead/PdfReader/ViewModels/PdfImageViewerDataSource.cs?at=default

BR,
Misha U.

**Comment by onkar1987** [comment]
Thank you for reply Misha. I just wondered about how you installed this NuGet packages. I got the problem `The type or namespace name 'Caliburn' could not be found (are you missing a using directive or an assembly reference?)`

How to use this?
`[xml]$packages = gc "{Your project path}\packages.config"
$packages.packages.package | % { Install-Package -id $($_.id) -Version $($_.version) }`

once I try to execute the second line it gives me below error
Install-Package : Unable to find package 'BugSense.WP8'.
At line:1 char:1
- Install-Package BugSense.WP8
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

not by `PM> Install-Package BugSense.WP8` this also

thanks for help once again.
