### ISSUE TITLE
how to use MuPDF.WinRT in WP8

### ISSUE THREAD

**Issue by abcfree01** [MishaUliutin/MuPDF.WinRT#12]
can someone show me how to use MuPDF.WinRT in WP8 step by step? thank you very much!

**Comment by MishaUliutin** [comment]
Hi,

You could find there https://github.com/MishaUliutin/MuPDF.WinRT/issues/1#issuecomment-13975296 code example, or there is open source version of PDF reader for WP8 which uses MuPDF.WinRT https://bitbucket.org/mishauliutin/pdf-reader-for-wp8-public

https://bitbucket.org/mishauliutin/pdf-reader-for-wp8-public/src/0b292bd3094b95ef612315502e828ab4cbc0f4b8/PdfReader/ViewModels/PdfImageViewerDataSource.cs?at=default

Best Regards,
Misha Uliutin

**Comment by abcfree01** [comment]
Hi,
Thanks a lot for your reply! I'll try again.

Br.
Qi Xiuping
