### ISSUE TITLE
MUPDF for Windows Phone not compiling

### ISSUE THREAD

**Issue by atulgit** [MishaUliutin/MuPDF.WinRT#13]
I am using mupdf for Windows Phone but I am not able to find any test project WP8. Only I see is the Windows RT component for Windows Phone 8 which also not compiling properly. When I am compiling, it is unable to find some files and symbols in the Windows RT component project. So if there any solution, any help would be appreciated.

**Comment by MishaUliutin** [comment]
Hi,
Sorry for the quite difficult build steps yet (I am working now on new version with simpler build steps), but you could find step by step instruction for building there https://github.com/MishaUliutin/MuPDF.WinRT/issues/1 (and some code examples). MuPDF.WinRT is used by this project https://bitbucket.org/mishauliutin/pdf-reader-for-wp8-public (this class https://bitbucket.org/mishauliutin/pdf-reader-for-wp8-public/src/a6e2ae0a63c24e75afc8eb405ad080c1c158dd5d/PdfReader/ViewModels/PdfImageViewerDataSource.cs?at=default)

Best regards,
Misha Uliutin

**Comment by atulgit** [comment]
Thaks for your kind reply Misha. I found the sample project for Windows Phone. It is having some missing references like Microsoft.Live, Bug-sense etc, so it is not compiling. Can you send me the fully compiled sample project for WP8??

**Comment by MishaUliutin** [comment]
We are using Nuget (http://www.nuget.org/) for third-party components for those project, so just install it and run such script in your Package Manager Console

```
[xml]$packages = gc "{Your project path}\packages.config"
$packages.packages.package | % { Install-Package -id $($_.id) -Version $($_.version) }
```
