### ISSUE TITLE
Blurry PDFs

### ISSUE THREAD

**Issue by JordanDavies** [MishaUliutin/MuPDF.WinRT#15]
Hi,

We're using your MuPDF library in our Windows Store app but have noticed PDFs become blurry and hard to read at certain zoom levels.

 Is this a know bug? Is there anything we can do about this?

Thanks.

**Comment by MishaUliutin** [comment]
Hi,
I don't know such issue, but actually quality of result picture depends on PDF quality, dpi (MuPDFDoc.Create method, resolution parameter - not directly depend, but influence on result picture size), size of picture that you choose for render page and your zoom algorithm.

Best Regards,
Misha Uliutin
