### ISSUE TITLE
Access Violation Exception 

### ISSUE THREAD

**Issue by atulgit** [MishaUliutin/MuPDF.WinRT#16]
Hi,
I am loading one page from isolated store and rendering with mupdf and then next after sliding the screen. For some PDF's it is giving me AccessViolation Exception. Pages of PDF are quite heavy in size e.g 4-5 MB.

I am not able to find the reason because the exception occurring is also not cachable in try catch block.
Plz help me out.

Thanks

**Comment by MishaUliutin** [comment]
Hi,
on of possible reason of such exception could be out of memory, could you send file to mishacertificate at gmail.com and what device do you use (or settings for emulator).

Best Regards,
Misha Uliutin
