### ISSUE TITLE
use in windows phone 8

### ISSUE THREAD

**Issue by tfzxyinhao** [MishaUliutin/MuPDF.WinRT#17]
After Complile this library for windows phone ,i found that this library passing row rgb data to user,but convert it to image is too hard,is there have some method to convert ?

**Comment by MishaUliutin** [comment]
Hi,
The simplest way now is to use WriteableBitmap class (http://msdn.microsoft.com/ru-ru/library/system.windows.media.imaging.writeablebitmap(v=vs.110).aspx)

``` C#
        private void DrawFirstPage()
        {
            var data = GetPDFFileData();
            using (var document = Document.Create(
                data.AsBuffer(), // - file
                DocumentType.PDF, // type
                160) // - dpi
                )
            {
                MuPDFWinRT.Point size = document.GetPageSize(0);
                var image = new WriteableBitmap(size.X, size.Y);
                document.DrawPage(0, image.PixelBuffer, 0, 0, size.X, size.Y, false);
                image.Invalidate();
                //_test - image
                _test.Source = image;
            }
        }

        private byte[] GetPDFFileData()
        {
            using (var stream = typeof(MainPage).GetTypeInfo().Assembly
                .GetManifestResourceStream("TestWinRTProj.1.pdf"))
            {
                var buff = new byte[stream.Length];
                stream.Read(buff, 0, buff.Length);
                return buff;
            }
        }
```

or do you want picture in other format then rgb?

P.S.
There is open source version of PDF reader for WP8 which uses MuPDF.WinRT https://bitbucket.org/mishauliutin/pdf-reader-for-wp8-public

https://bitbucket.org/mishauliutin/pdf-reader-for-wp8-public/src/0b292bd3094b95ef612315502e828ab4cbc0f4b8/PdfReader/ViewModels/PdfImageViewerDataSource.cs?at=default

Best Regards,
Misha Uliutin
