### ISSUE TITLE
TypeLoadException when using Document.Create()

### ISSUE THREAD

**Issue by edgar89** [MishaUliutin/MuPDF.WinRT#21]
Hello, 
 I've been struggling with this library since Yesterday morning because I can't load any document with it. Whenever I reach the instruction:

 this.Document = Document.Create(Source, DocumentType.PDF, (int)ScreenManager.ScreenDpi);

the application crashes with TypeLoadException, InnerException: Interface not registered, HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG). Required Windows Runtime Type 'MuPDFWinRT.Document' is not registered.

I searched on the web for this issue and everything seemd to point to a misconfiguration in project properties but I think I created them correctly. (See configuration screen here: https://dl.dropboxusercontent.com/u/73691727/config.PNG) 

In my project reference I checked the winmd file (not the dll). In fact if I try to add a reference to the dll I obtain an error: "Cannot add a reference to <dll_name>. Check if assembly or COM component is valid"

I'm aware that this is not a lib issue per-se but I think you're the only one who can light this up for me (and for other users who will eventually experience the issue in the future)

Thanks
Giuseppe

**Comment by MishaUliutin** [comment]
Hi,
sorry for delay with answer, could you please check your issue with this #18?

BTW
you could always look in this https://bitbucket.org/mishauliutin/pdf-reader-for-wp8-public example

BR,
Misha U
