### ISSUE TITLE
Windows Phone 8.1

### ISSUE THREAD

**Issue by rudyzeinoun** [MishaUliutin/MuPDF.WinRT#24]
Can you provide binaries for Windows Phone 8.1? Building from source is troublesome on this platform and the store is requiring AppContainerCheck on the current Win8 (WinRT) DLLs.

**Comment by rudyzeinoun** [comment]
Never mind... I found the instructions in issue #1 and was able to successfully compile while adding AppContainerCheck to the linker.

**Comment by vikrantThakur** [comment]
hii when i add mupdfWinrt.Winmd my project(windows phone 8.1 WPF),it runs successfully and everything goes smoothly but the MuPdfWinRT api fails the test when i upload it to store it shows app container check.So what should i do now
Can Anyone help me out.
