### ISSUE TITLE
PhoneBootStrapper namespace in windows phone

### ISSUE THREAD

**Issue by GDEVENDRAK** [MishaUliutin/MuPDF.WinRT#26]
I'm trying to use your MuPDF reader for Windows phone 8 & I tried to build your sample project from
Bitbucket [ https://bitbucket.org/mishauliutin/pdf-reader-for-wp8-public/downloads ]

When I tried to build the project I am getting error namespace 'PhoneBootstrapper' could not be found on PhoneBootstrapper class. I'm not sure about the PhoneBootstrapper class or Is there any thing else that I'm missing.

![untitled](https://cloud.githubusercontent.com/assets/4927052/4989682/3893c194-69a2-11e4-915c-142d33d80303.png)

 I added few more details Here http://goo.gl/T2ly4N
So, Could you please suggest me regarding the issue. Thanks

**Comment by MishaUliutin** [comment]
Hi,
it's part of MVVM framework Caliburn.Micro https://caliburnmicro.codeplex.com/, just download all dependencies with Nuget

BR,
Misha U
