### ISSUE TITLE
Is MuPDF.WinRT available for WP8?

### ISSUE THREAD

**Issue by schbook** [MishaUliutin/MuPDF.WinRT#5]
When add reference of the MuPDFWinRT.dll compiled under WP8 Solution, it alerts unable to add an incompatible reference.

**Comment by MishaUliutin** [comment]
Hi,
Sorry for delay with answer. Yes, MuPDF.WinRT is available for WP8. It looks like you added MuPDFWinRT.dll with wrong platform. Actually you have to have two version of MuPDFWinRT.dll - x86 and this version mostly for running your app at WP emulator, and ARM version and this version for app which you deploy in WP8 device. So, in your .csproj file you should have something like this

```
<Reference Include="MuPDFWinRT, Version=255.255.255.255, Culture=neutral, processorArchitecture=MSIL" Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
  <SpecificVersion>False</SpecificVersion>
  <HintPath>..\xternals\MuPDF\x86\MuPDFWinRT.winmd</HintPath>
</Reference>
<Reference Include="MuPDFWinRT, Version=255.255.255.255, Culture=neutral, processorArchitecture=MSIL" Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
  <SpecificVersion>False</SpecificVersion>
  <HintPath>..\xternals\MuPDF\x86\MuPDFWinRT.winmd</HintPath>
</Reference>
<Reference Include="MuPDFWinRT, Version=255.255.255.255, Culture=neutral, processorArchitecture=MSIL" Condition=" '$(Configuration)|$(Platform)' == 'Debug|ARM' ">
  <SpecificVersion>False</SpecificVersion>
  <HintPath>..\xternals\MuPDF\ARM\MuPDFWinRT.winmd</HintPath>
</Reference>
<Reference Include="MuPDFWinRT, Version=255.255.255.255, Culture=neutral, processorArchitecture=MSIL" Condition=" '$(Configuration)|$(Platform)' == 'Release|ARM' ">
  <SpecificVersion>False</SpecificVersion>
  <HintPath>..\xternals\MuPDF\ARM\MuPDFWinRT.winmd</HintPath>
</Reference>
```

Best Regards,
Misha Uliutin

**Comment by schbook** [comment]
I just corrected the .csproj file and it works well now, thank you very much.

**Comment by abcfree01** [comment]
can someone show me how to use MuPDF.WinRT in WP8 step by step? thank you very much!

**Comment by 81093507689** [comment]
Hello sir i have download your "mishauliutin-pdf-reader-for-wp8-public" project 
When i m open any pdf file from SDCARD List then error message is and not open any pdf file 
Can not open file - testPath1.:(
OK button 
please Solve my problem I am waiting Your replay 
thanks
