### ISSUE TITLE
Issues with Windows App Certification Kit

### ISSUE THREAD

**Issue by hungntm** [MishaUliutin/MuPDF.WinRT#6]
Hello Misha Uliutin,

I developed a Windows Store App in C#, and add MuPDFWinRT as reference. Then I tried to use <b>Windows App Certification Kit</b> to check if my app is suitable for <b>Windows Store</b>. But I got some errors as below:
<i>API GetModuleFileNameW in kernel32.dll is not supported for this application type. MuPDFWinRT.dll calls this API.
API LoadLibraryExW in kernel32.dll is not supported for this application type. MuPDFWinRT.dll calls this API.
API LoadLibraryW in kernel32.dll is not supported for this application type. MuPDFWinRT.dll calls this API.</i>
I don't know where you used these APIs and what these APIs are using for. Can you give me some advice?

Thanks and Best Regards,

Hung Nguyen

**Comment by MishaUliutin** [comment]
Hi Hung Nguyen,
Do you use Debug or Release version of library?

Best Regards,
Misha Uliutin

**Comment by hungntm** [comment]
Hi Misha Uliutin,

I built and used the Release version of library. I downloaded from https://github.com/libreliodev/MuPDF.WinRT which is forked from your library (https://github.com/MishaUliutin/MuPDF.WinRT).

Best Regards,

Hung Nguyen

**Comment by MishaUliutin** [comment]
Hi Hung Nguyen,

First off all could you please merge the latest version of library to your fork.
Second, could you please check that you use the latest version of Windows App Certification Kit.
The last, I am sorry for annoying, but, do you completely sure that you use release version of dll, when you run Windows App Certification Kit for your app? (I get such errors only when I use debug version).

P.S.
You could download my test app from this link: https://skydrive.live.com/?cid=83b239d3a039f8e8&id=83B239D3A039F8E8%21650&authkey=!AHRDiLCBtjJDZHs

Best Regards,
Misha Uliutin

**Comment by hungntm** [comment]
Hello Misha Uliutin,

I merged the latest version of your library to my fork. It worked fine and it passed <b>Windows App Certification Kit</b>'s test.

How nice of you, thanks very much!

Best Regards,

Hung Nguyen

**Comment by sai4rall** [comment]
hi Misha Uliutin,
I'm new to this project as well as i'm new to winrt development will you please tell me how to merge the library to my project

**Comment by vikrantThakur** [comment]
hello Misha Uliutin

I have merged your libraries in my wp8.1 App project.But it fails certification test.
details are:-

The overloaded methods Create of type MuPDFWinRT.__IDocumentStatics in file MuPDFWinRT.winmd have the same number of in parameters without one that has DefaultOverloadAttribute. Exactly one method overload must have DefaultOverloadAttribute.
The overloaded methods Create of type MuPDFWinRT.Document in file MuPDFWinRT.winmd have the same number of in parameters without one that has DefaultOverloadAttribute. Exactly one method overload must have DefaultOverloadAttribute.

can you please tell what exactly i have to do.

best regards,
Vikrant Thakur
