### ISSUE TITLE
one exception happen when try to show one pdf file on WP8 device?

### ISSUE THREAD

**Issue by Amazing110** [MishaUliutin/MuPDF.WinRT#7]
Hi Misha Uliutin,

I builded the lib sucessfully, but I got one error when tried to show one pdf file with your lib in Windows phone8 dev env, the testing code is  yours like following:

```
    private byte[] GetPDFFileData()
    {
        using (var stream = typeof(MainPage).GetTypeInfo().Assembly
            .GetManifestResourceStream("AmazingPdf.test.pdf"))
        {
            var buff = new byte[stream.Length];
            stream.Read(buff, 0, buff.Length);
            return buff;
        }
    }


    private void DrawFirstPage()
    {
        var data = GetPDFFileData();
        using (var document = Document.Create(
            data.AsBuffer(), // - file
            DocumentType.PDF, // type
            160) // - dpi
            )
        {
           ............
        }
    }
```

The exception happens in below code:
            using (var document = Document.Create(
                data.AsBuffer(), // - file
                DocumentType.PDF, // type
                160) // - dpi
                )
It says "The parameter is incorrect.", I check the "data" var, its length is 1060708,  could you pls show me how I can slove this problem? 
Thanks

**Comment by MishaUliutin** [comment]
Hi,
Could you send me this file to mishacertificate@gmail.com please?

Best Regards,
Misha Uliutin

**Comment by Amazing110** [comment]
Misha,

It seems it caused by the GB2312 document already be damaged, caused by the WP8 IDE will convert the GB2312 to unicode, but the transformation caused the pdf be damaged, I also can't open it with Adobe pdf reader in PC.

I wil try to put the PDF to isolated storage and try again.

The GB2312 pdf file already sent to your mailbox, please check it.

**Comment by MishaUliutin** [comment]
Hi,
Sorry for delay with answer, I've just finished test your file and did not find any problem with your file. It looks like you did not compile library in a proper way (sorry for a little bit difficult compile proccess). Could you please recompile library?

P.S.
My test application with your file:
https://skydrive.live.com/?cid=83B239D3A039F8E8&id=83B239D3A039F8E8%21647

Best Regards,
Misha Uliutin
