### ISSUE TITLE
Setting up VS2012 (express) solution to compile and reference muPDF WinRT

### ISSUE THREAD

**Issue by P5music** [MishaUliutin/MuPDF.WinRT#8]
Hello, 
I created a test solution in my VS2012 (express) environment and added a MuPDFWinRT project in it.
I added reference to MuPDFWinRT but at compile time I get those errors about fitz.h.
I installed git on my computer and dragged the MuPDFWinRT folder in the git user interface so it created a local repository.
Now, I ask what I have to do to have all files and compile it? I am new to git so I did not understand the other threads about this issue. 
Thank you in advance if you can help me.

**Comment by MishaUliutin** [comment]
Hi,
Sorry for delay in answer. There is not any difficult issues with git. Git is really easy and simple. You could read about git in this good book http://git-scm.com/book, but actually I have not used any difficult git features (only submodules http://git-scm.com/book/en/Git-Tools-Submodules). 
You could find step by step guide here https://github.com/MishaUliutin/MuPDF.WinRT/issues/1#issuecomment-13975296 or I've added compiled binaries https://github.com/MishaUliutin/MuPDF.WinRT/tree/master/Binaries

Best Regards,
Misha Uliutin

**Comment by P5music** [comment]
Thank you for answering. 
I tried to download the missing mupdf sources and compile the projects according to your instructions (in that other thread) but I think I messed things up so I think it is better for me to use your compiled binaries. But I am not able to download them, I do not find any real file to download. Is a git command needed? Can you help me for this? Thanks in advance.

**Comment by MishaUliutin** [comment]
If you have already cloned my repository just:
- Run git bush
- Go to folder with project and run:
  
  ```
  $ git pull
  ```

or
-  Run git bush
-  Go to folder where you want download project (e.g. in my case this d:\PetProjects)
  
  ```
  $ cd /d/PetProjects
  ```
- Run:
  
  ```
  $ git clone git://github.com/MishaUliutin/MuPDF.WinRT.git
  ```

**Comment by P5music** [comment]
Thank you so much. I tried this:
[code]
C:\Users\myuser\Documents\Visual Studio 2012\Projects\MuPDF.WinRT-master [master +9 ~0 -0 !]> git pull git://github.com/MishaUliutin/MuPDF.WinRT.git
remote: Counting objects: 279, done.
remote: Compressing objects: 100% (150/150), done.
remote: Total 279 (delta 126), reused 278 (delta 125)
Receiving objects: 100% (279/279), 43.70 MiB | 375 KiB/s, done.
Resolving deltas: 100% (126/126), done.
From git://github.com/MishaUliutin/MuPDF.WinRT
- branch            HEAD       -> FETCH_HEAD
  error: Untracked working tree file '.gitattributes' would be overwritten by merge.
  C:\Users\myuser\Documents\Visual Studio 2012\Projects\MuPDF.WinRT-master [master +0 ~0 -43 | +9 ~0 -0 !]>
  [/code]

I checked that folder and the files were timestamped with old timestamp, not with current time, so I think that error was fatal, no repository pulled?

**Comment by MishaUliutin** [comment]
Please run in folder:

```
    $ git fetch --all
    $ git reset --hard origin/master
```

**Comment by P5music** [comment]
sorry, running the first command I got

Fetching origin
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
Fetching upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch upstream

**Comment by MishaUliutin** [comment]
Could you delete your current MuPDF.WinRT git repository and clone it again?

**Comment by P5music** [comment]
Thank you for your patience.

I cloned the repo anew but when I try to compile my test app (which has reference to the mupdfWinRT project inside the solution) I get from Visual Studio:
Errore  1   Impossibile trovare il file di metadati 'C:\Users\myuser\Documents\Visual Studio 2012\Projects\mupdfWinRT\MuPDF.WinRT\Win8\Win32\Debug\MuPDFWinRT.winmd'    C:\Users\myuser\Documents\Visual Studio 2012\Projects\App2\App2\CSC App2

and the usual “fitz.h not found” error.
How to reference the included binaries (are they included, aren't)? I am not an expert, maybe I am wrong in silly ways, so every suggestion is welcome.

**Comment by MishaUliutin** [comment]
What kind of project do you want create? (Windows Phone 8 or Windows Store App)

**Comment by P5music** [comment]
I would like to create a Windows Store App.

**Comment by MishaUliutin** [comment]
You could download simple Windows Store App with MuPDF.WinRT there: https://skydrive.live.com/redir?resid=83B239D3A039F8E8!1123

**Comment by P5music** [comment]
Thank you very much. It seems to be working. Best regards.

**Comment by MishaUliutin** [comment]
You are welcome :)
