### ISSUE TITLE
Unable to build thirdparty

### ISSUE THREAD

**Issue by Angels200** [MishaUliutin/MuPDF.WinRT#9]
Hi Misha,

First of all thanks for your work. However after spending hours trying to build the third party mupdf, the result fails. Could you please post a build of that package it will be very helpfull

Thanks in advance

**Comment by MishaUliutin** [comment]
Hi,
Sorry for difficult build process yet, you could find step by step guide here https://github.com/MishaUliutin/MuPDF.WinRT/issues/1#issuecomment-13975296 or I've added compiled binaries https://github.com/MishaUliutin/MuPDF.WinRT/tree/master/Binaries
